[editor]
end-of-line-diagnostics = "disable"

[editor.lsp]
enable              = true
snippets            = true
display-messages    = false
auto-signature-help = false
display-inlay-hints = true

[editor.inline-diagnostics]
cursor-line = "disable" # show warnings and errors on the cursorline inline
max-diagnostics = 8
other-lines = "disable"
prefix-len = 2
max-wrap = 20

[keys.normal.space]
i = ":toggle lsp.display-inlay-hints"
